### ISSUE TITLE
Supported features tracking

### ISSUE THREAD

**Issue by mxpv** [mxpv/openusd#1]
## Reading usdc (binary crate files)

- [x] Read structural data (headers, sections, tokens, etc) - 4d5072c7e72fcf02b506a7c5573bcb476c5e42cd, see [dump_usdc.rs](https://github.com/mxpv/openusd/blob/ae5088ad9ca30df8443aab20f5d9e0de2777b570/examples/dump_usdc.rs#L1) example.
  - [ ] Support older file formats (`== 0.1.0` and `< 0.4.0`)
  - [ ] Support chunked `lz4` decompression (important for large binary files, need to find proper usd file).
- [x] Read spec hierarchy - ae5088ad9ca30df8443aab20f5d9e0de2777b570
- [x] Read basic types
  - [x] Bool
  - [x] Uchar
  - [x] Int
  - [x] Uint
  - [x] Int64
  - [x] Uint64
  - [x] Half
  - [x] Float
  - [x] Double
  - [x] String
  - [x] Token
  - [x] AssetPath
- [x] Read complex types (arrays, compressed arrays, etc)
  - [x] Bool array
  - [x] Uchar array 
  - [x] Int array - 53e4349bf1866a1202f5fd7b576ffee873181f15
  - [x] Uint array - 53e4349bf1866a1202f5fd7b576ffee873181f15
  - [x] Int64 array
  - [x] Uint64 array
  - [x] Float array
  - [x] Quat{d,f,h}
  - [x] Quat{d,f,h} arrays
  - [x] HVec{2,3,4}
  - [x] HVec{2,3,4} arrays
  - [x] FVec{2,3,4} - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] FVec{2,3,4} arrays - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] IVec{2,3,4} - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] IVec{2,3,4} arrays - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] DVec{2,3,4} - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] DVec{2,3,4} arrays - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] Matrix{2,3,4}d - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] Matrix{2,3,4}d inlined - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] Matrix{2,3,4}d arrays - a0ff4d9bd16082660da7074a45ff9108da24685c
  - [x] Dictionary (custom data types)
  - [x] Token arrays - 53e4349bf1866a1202f5fd7b576ffee873181f15
  - [x] #3
- [x] ListOps
  - [x] TokenListOp
  - [x] StringListOp
  - [x] PathListOp
  - [x] ReferenceListOp
  - [x] IntListOp
  - [x] Int64ListOp
  - [x] UIntListOp
  - [x] UInt64ListOp
  - [x] PayloadListOp - 6ea5378e860134e9ec1fccdf063f9dcdff64ce82
- [x] Read `SDF` types
  - [x] PathVector
  - [x] TokenVector
  - [x] Specifier
  - [x] Permission
  - [X] Variability
  - [x] VariantSelectionMap
  - [x] TimeSamples
  - [x] Payload - 6ea5378e860134e9ec1fccdf063f9dcdff64ce82
  - [x] DoubleVector
  - [x] LayerOffsetVector - 6b854fdab9f8d0fa3b9ec33fbbcf014b42956595
  - [x] StringVector - 6b854fdab9f8d0fa3b9ec33fbbcf014b42956595
  - [x] ValueBlock
  - [x] Value
  - [x] UnregisteredValue
  - [x] UnregisteredValueListOp
  - [x] TimeCode
  - [x PathExpression

# Reading usda
  - [x] Tokenizer
  - [x] Reader
